### ISSUE TITLE
Try kotlinx synthetic and reduce the verbose code

### ISSUE THREAD

**Issue by sleepylee** [Tuubz/SurveyApp#18]
![image](https://user-images.githubusercontent.com/13435717/45399030-cefbc900-b670-11e8-8a60-14d5ab9473f4.png)
https://kotlinlang.org/docs/tutorials/android-plugin.html

**Comment by Tuubz** [comment]
Very convenient : https://github.com/Tuubz/SurveyApp/pull/21
